# Generated by Django 3.2.13 on 2022-10-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_review_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like_users',
        ),
    ]
